import Head from 'next/head'
import Image from 'next/image'
import Acordeon from '../components/Acordeon'
import BlocHero from '../components/BlocHero'
import Test from '../components/Test'
import Video from '../components/Video'
import styles from '../styles/Home.module.css'

export default function Home() {

  return (
    <div className="bg-white dark:bg-black">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

 <Video />
 <BlocHero />

 <Acordeon />

    </div>
  )
}
