import Head from 'next/head'
import Image from 'next/image'
import Acordeon from '../components/Acordeon'
import Bestsales from '../components/Bestsales'
import BlocHero from '../components/BlocHero'
import Test from '../components/Test'
import Video from '../components/Video'
import styles from '../styles/Home.module.css'
import dbConnect from '../utils/mongo';
import { getData } from '../utils/fetchData';

export default function Home(props) {

  return (
    <div className="bg-white dark:bg-black ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

 <Video />
 <div  className='max-w-screen-xl mx-auto'>
 <BlocHero />
 <Bestsales products={props.products}/>
  <Acordeon />
 </div>


    </div>
  )
}



export const getServerSideProps = async ({query}) => {
  await dbConnect()
  
  const category = query.category || 'all'
  const sort = query.sort || ''
  const search = query.search || 'all'
  const brand = query.brand || 'all'

  const res = await getData(
    `products?category=${category}&brand=${brand}&sort=${sort}&title=${search}&limit=3`
  )
  const jordan = await getData(
    `products?category=${category}&brand=${brand}&sort=${sort}&title=${"jordan"}`
  )
  
  return {
    props: {
      products: res.products,
      sliderItems: jordan.products.reverse()
    },
  };
};

